export const dynamic = 'force-dynamic'
import { verifyToken } from '../../../../lib/verifyToken.js'
import { apiError }    from '../../../../lib/apiError.js'
import { connectDB }   from '../../../../lib/mongodb.js'
import Case            from '../../../../lib/models/Case.js'

export async function POST(request) {
  let decoded
  try { decoded = await verifyToken(request) } catch { return apiError('Unauthorized', 401) }

  try {
    await connectDB()
    // Clear existing demo seed cases for this user
    await Case.deleteMany({ uid: decoded.uid, batch_id: 'demo_seed' })

    const SEED_CASES = [
      // ── CRITICAL (rank 1-5, score 85-95) ────────────────────────────────────
      {
        client_name: 'Maria Santos',
        case_type: 'eviction',
        summary: 'Single mother of two (ages 4 and 7) facing eviction hearing in 48 hours. Landlord claims $2,800 unpaid rent during COVID-era hardship period. Section 8 housing voucher approval is pending — would resolve balance entirely.',
        deadline_days: 2,
        vulnerability_flags: { minor_children: true, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 94,
        score_breakdown: { deadline_points: 36, vulnerability_points: 25, case_type_points: 20, similarity_points: 13 },
        priority_reason: 'Eviction hearing in 48 hours with two minor children at risk of homelessness. Section 8 voucher approval pending — emergency stay would allow voucher process to complete. Language barrier limits client self-advocacy.',
        similar_cases: [
          { id: 'h001', outcome: 'Emergency stay granted — voucher approved within 30 days', similarity: 0.91 },
          { id: 'h002', outcome: 'Hearing continued 45 days — matter resolved', similarity: 0.87 },
        ],
        recommendation: 'File emergency stay motion immediately citing minor children and pending housing voucher. Arrange certified interpreter. Contact housing authority to expedite Section 8 approval letter.',
        rank: 1,
        status: 'pending',
      },
      {
        client_name: 'Amara Diallo',
        case_type: 'eviction',
        summary: 'Domestic violence survivor served eviction notice while in DV shelter with two children. Landlord unaware client fled for safety. Emergency housing voucher application submitted 3 days ago — approval pending.',
        deadline_days: 1,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 91,
        score_breakdown: { deadline_points: 38, vulnerability_points: 23, case_type_points: 20, similarity_points: 10 },
        priority_reason: 'Client is a domestic violence survivor currently in shelter with children. Eviction notice issued during active protective order — DV protections apply. Emergency housing pathway exists but requires immediate legal intervention.',
        similar_cases: [
          { id: 'h003', outcome: 'Eviction stayed under DV tenant protection statute', similarity: 0.88 },
        ],
        recommendation: 'File emergency motion citing domestic violence tenant protections. Gather protective order documentation from shelter advocate. Request hearing continuance pending DV housing voucher.',
        rank: 2,
        status: 'pending',
      },
      {
        client_name: 'James Okafor',
        case_type: 'immigration',
        summary: 'Nigerian national with approved asylum claim facing removal proceedings in 72 hours. Final removal order issued despite pending appeal — potential attorney error in deadline filing.',
        deadline_days: 3,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['Attorney correspondence records', 'Timeline of appeal filing dates'],
        priority_score: 87,
        score_breakdown: { deadline_points: 34, vulnerability_points: 5, case_type_points: 20, similarity_points: 13 },
        priority_reason: 'Removal in 72 hours despite approved asylum status. Attorney error may have caused missed appeal deadline — creates additional legal basis for emergency stay. Three CourtListener precedents support emergency stay in comparable situations.',
        similar_cases: [
          { id: 'h004', outcome: 'Emergency stay granted — appeal reinstated', similarity: 0.85 },
          { id: 'h005', outcome: 'Removal stayed pending attorney error review', similarity: 0.82 },
        ],
        recommendation: 'File emergency motion to stay removal immediately. Investigate attorney error claim as basis for ineffective assistance. Contact asylum office to flag approved status on record.',
        rank: 3,
        status: 'pending',
      },
      {
        client_name: 'Rosa Chen',
        case_type: 'eviction',
        summary: 'Elderly Vietnamese woman (72) with kidney dialysis three times weekly facing eviction for noise complaint. Landlord failed to provide reasonable accommodation notice. Medical equipment noise deemed "excessive" by building manager.',
        deadline_days: 2,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: true },
        missing_info: [],
        priority_score: 89,
        score_breakdown: { deadline_points: 36, vulnerability_points: 18, case_type_points: 20, similarity_points: 15 },
        priority_reason: 'Active ADA accommodation violation — landlord failed to provide required notice before proceeding with eviction. Medical necessity creates compelling defense. Eviction in 48 hours without accommodation review violates Fair Housing Act.',
        similar_cases: [
          { id: 'h006', outcome: 'Eviction dismissed — ADA accommodation violation upheld', similarity: 0.89 },
        ],
        recommendation: 'File emergency motion citing ADA accommodation violation and Fair Housing Act. Document dialysis equipment as medical necessity. Request immediate stay pending accommodation review.',
        rank: 4,
        status: 'pending',
      },
      {
        client_name: 'Darius Washington',
        case_type: 'employment',
        summary: 'Former hospital IT manager wrongfully terminated after reporting HIPAA violations. COBRA insurance deadline tomorrow — missing this date means 18-month gap in coverage during ongoing cancer treatment.',
        deadline_days: 1,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: ['COBRA election form', 'HIPAA complaint documentation'],
        priority_score: 85,
        score_breakdown: { deadline_points: 38, vulnerability_points: 8, case_type_points: 14, similarity_points: 10 },
        priority_reason: 'COBRA election deadline tomorrow — missing this creates irreversible 18-month coverage gap during active cancer treatment. Whistleblower retaliation claim requires immediate EEOC filing. Dual deadline crisis.',
        similar_cases: [
          { id: 'h007', outcome: 'COBRA reinstated — retaliation claim settled', similarity: 0.79 },
        ],
        recommendation: 'Assist with COBRA election form submission today. File EEOC retaliation complaint before COBRA deadline. Begin wrongful termination documentation for civil claim.',
        rank: 5,
        status: 'pending',
      },

      // ── URGENT (rank 6-15, score 65-84) ─────────────────────────────────────
      {
        client_name: 'Chen Wei',
        case_type: 'wage_theft',
        summary: 'Restaurant kitchen worker owed $18,400 in unpaid overtime over 14 months. Employer closed business, filed bankruptcy, then reopened under LLC — appears to be fraudulent transfer to avoid wage claims.',
        deadline_days: 4,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 78,
        score_breakdown: { deadline_points: 32, vulnerability_points: 5, case_type_points: 16, similarity_points: 12 },
        priority_reason: 'Statute of limitations on wage claim expires in 4 days. Fraudulent transfer to new LLC requires urgent legal action to preserve claim against successor entity. Historical cases show 89% success rate when filed before business transfer completed.',
        similar_cases: [
          { id: 'h008', outcome: 'Wage claim upheld — successor liability applied', similarity: 0.86 },
        ],
        recommendation: 'File wage claim with Labor Commissioner immediately before 4-day deadline. File fraudulent transfer complaint against new LLC as successor entity. Attach payroll evidence as exhibits.',
        rank: 6,
        status: 'pending',
      },
      {
        client_name: 'Fatima Al-Hassan',
        case_type: 'custody',
        summary: 'Mother seeking modification of custody order after father relocated to another state with children without court approval. Children enrolled in new school district — unauthorized relocation violates existing order.',
        deadline_days: 5,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 74,
        score_breakdown: { deadline_points: 30, vulnerability_points: 18, case_type_points: 18, similarity_points: 8 },
        priority_reason: 'Unauthorized relocation of children violates existing custody order — 5-day window for emergency motion before school enrollment becomes established precedent. Historical outcomes strongly favor immediate motion.',
        similar_cases: [
          { id: 'h009', outcome: 'Emergency return order granted within 48 hours', similarity: 0.83 },
        ],
        recommendation: 'File emergency motion to enforce existing custody order and compel return of children. Request order to show cause for contempt. Contact school district in current location.',
        rank: 7,
        status: 'pending',
      },
      {
        client_name: 'Jorge Martinez',
        case_type: 'eviction',
        summary: 'Mexican farm worker family of five facing eviction from employer-provided housing after agricultural injury claim. Employer combining eviction with termination of workers’ comp claim — retaliatory pattern documented.',
        deadline_days: 6,
        vulnerability_flags: { minor_children: true, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 72,
        score_breakdown: { deadline_points: 28, vulnerability_points: 23, case_type_points: 14, similarity_points: 7 },
        priority_reason: 'Retaliatory eviction following workers’ compensation claim is prohibited. Family of five with three children at risk. Language barrier limits client’s ability to understand notice requirements.',
        similar_cases: [
          { id: 'h010', outcome: 'Retaliatory eviction dismissed — WC claim preserved', similarity: 0.81 },
        ],
        recommendation: 'File retaliatory eviction defense immediately. File workers’ comp retaliation complaint with Labor Commissioner. Arrange Spanish-speaking attorney for hearing.',
        rank: 8,
        status: 'pending',
      },
      {
        client_name: 'Priya Patel',
        case_type: 'employment',
        summary: 'Software engineer filed EEOC charge for gender and national origin discrimination after being passed over for promotion despite higher qualifications. EEOC issued right-to-sue letter 87 days ago — 90-day filing deadline approaching.',
        deadline_days: 7,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 66,
        score_breakdown: { deadline_points: 26, vulnerability_points: 5, case_type_points: 12, similarity_points: 10 },
        priority_reason: '90-day right-to-sue filing deadline expires in 7 days — missing this is jurisdictional and bars all federal claims permanently. Strong evidentiary record with internal emails and performance reviews.',
        similar_cases: [
          { id: 'h011', outcome: 'Complaint filed timely — case proceeded to discovery', similarity: 0.77 },
        ],
        recommendation: 'File Title VII discrimination complaint in federal district court before 7-day deadline. Attach EEOC charge and right-to-sue letter. Include internal promotion comparison documentation.',
        rank: 9,
        status: 'pending',
      },
      {
        client_name: 'Antoine Dubois',
        case_type: 'immigration',
        summary: 'Haitian national with pending asylum claim whose work authorization expired during USCIS processing delay. Employer terminated for lack of authorization — USCIS issued auto-extension notice 3 months later but employer didn’t reinstate.',
        deadline_days: 7,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['USCIS auto-extension notice copy', 'Employment termination letter'],
        priority_score: 68,
        score_breakdown: { deadline_points: 26, vulnerability_points: 5, case_type_points: 18, similarity_points: 8 },
        priority_reason: 'Wrongful termination claim based on USCIS auto-extension rules — employer failed to honor automatic EAD extension. Employment rights violation with 7-day statute of limitations for state complaint.',
        similar_cases: [
          { id: 'h012', outcome: 'Reinstatement ordered — back pay awarded', similarity: 0.74 },
        ],
        recommendation: 'File state employment discrimination complaint before deadline. Forward USCIS auto-extension notice to employer with reinstatement demand letter. Request back pay for wrongful termination period.',
        rank: 10,
        status: 'pending',
      },
      {
        client_name: 'Yolanda Brooks',
        case_type: 'custody',
        summary: 'Mother with fibromyalgia seeking to modify custody arrangement after father refuses to administer prescribed medications to 8-year-old with Type 1 diabetes. Child hospitalized twice in past month — medical neglect documented.',
        deadline_days: 6,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: true },
        missing_info: [],
        priority_score: 73,
        score_breakdown: { deadline_points: 28, vulnerability_points: 23, case_type_points: 12, similarity_points: 10 },
        priority_reason: 'Child safety emergency — documented medical neglect of diabetic child requiring insulin management. Two hospitalizations in past month create urgent basis for custody modification. Medical records support immediate action.',
        similar_cases: [
          { id: 'h013', outcome: 'Emergency custody modification granted — medical neglect upheld', similarity: 0.86 },
        ],
        recommendation: 'File emergency motion for temporary sole custody citing medical neglect. Submit hospital records and physician statement. Request emergency hearing within 48 hours.',
        rank: 11,
        status: 'pending',
      },
      {
        client_name: 'Miguel Reyes',
        case_type: 'wage_theft',
        summary: 'Construction contractor withheld $12,600 from undocumented workers for “equipment rental fees” that were never disclosed in work agreements. Workers afraid to file — this client agreed to proceed.',
        deadline_days: 5,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 71,
        score_breakdown: { deadline_points: 30, vulnerability_points: 5, case_type_points: 14, similarity_points: 12 },
        priority_reason: 'Wage theft with 5-day filing deadline before statute runs. Workers’ immigration status irrelevant to wage claim under state law. Historical cases show 94% recovery rate when filed with documentation.',
        similar_cases: [
          { id: 'h014', outcome: 'Wages recovered — contractor license suspended', similarity: 0.82 },
        ],
        recommendation: 'File wage claim with Labor Commissioner — state wage laws protect all workers regardless of immigration status. Collect signed statements from other affected workers as witnesses.',
        rank: 12,
        status: 'pending',
      },
      {
        client_name: 'Diana Petrov',
        case_type: 'eviction',
        summary: 'Ukrainian refugee in Section 8 housing facing eviction for late rent — bank froze account due to name match on sanctions list (different person). Rent held in frozen account, landlord proceeding despite documentation.',
        deadline_days: 4,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: true },
        missing_info: [],
        priority_score: 76,
        score_breakdown: { deadline_points: 32, vulnerability_points: 12, case_type_points: 20, similarity_points: 12 },
        priority_reason: 'Bank freeze is an administrative error — client has documentation proving mistaken identity. Eviction in 4 days for non-payment caused by force majeure/government error. Strong equitable defense.',
        similar_cases: [
          { id: 'h015', outcome: 'Eviction stayed — bank error defense upheld', similarity: 0.79 },
        ],
        recommendation: 'File emergency stay citing impossibility defense. Provide bank correspondence to landlord and court. Contact OFAC to expedite account review — typically resolved within 24-48 hours with documentation.',
        rank: 13,
        status: 'pending',
      },
      {
        client_name: 'Keisha Thomas',
        case_type: 'employment',
        summary: 'Nursing assistant terminated after requesting FMLA leave for breast cancer diagnosis. Employer claimed position eliminated — three similar positions posted online two weeks later. Pattern of post-FMLA termination documented.',
        deadline_days: 5,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: ['FMLA request documentation', 'Employer written response'],
        priority_score: 67,
        score_breakdown: { deadline_points: 30, vulnerability_points: 5, case_type_points: 12, similarity_points: 10 },
        priority_reason: 'FMLA retaliation claim with 5-day deadline to file with DOL before two-year statute runs. Clear temporal proximity between FMLA request and termination. Job postings for same role support retaliatory motive.',
        similar_cases: [
          { id: 'h016', outcome: 'FMLA retaliation upheld — reinstatement and back pay awarded', similarity: 0.78 },
        ],
        recommendation: 'File FMLA retaliation complaint with DOL and state labor board. Preserve job posting screenshots as evidence. Notify employer in writing that FMLA claim is being pursued.',
        rank: 14,
        status: 'pending',
      },
      {
        client_name: 'Nguyen Van Hoa',
        case_type: 'immigration',
        summary: 'Vietnamese family on temporary protected status received deportation notice despite TPS extension filed 8 months ago. USCIS has no record of application — attorney may have failed to file.',
        deadline_days: 6,
        vulnerability_flags: { minor_children: true, language_barrier: true, medical_condition: false },
        missing_info: ['Prior TPS application copy', 'Attorney correspondence', 'Prior filing receipts'],
        priority_score: 69,
        score_breakdown: { deadline_points: 28, vulnerability_points: 10, case_type_points: 18, similarity_points: 8 },
        priority_reason: 'TPS application may not have been filed by prior attorney — potential malpractice creating urgent need to refile and challenge deportation notice. Family of four at risk with 6-day window.',
        similar_cases: [
          { id: 'h017', outcome: 'TPS reinstated — attorney error documented', similarity: 0.76 },
        ],
        recommendation: 'File new TPS application immediately with premium processing. File bar complaint against prior attorney. Request USCIS expedited review based on attorney error.',
        rank: 15,
        status: 'pending',
      },

      // ── DOCUMENTATION GAP (rank 16-20, score 55-70) ─────────────────────────
      {
        client_name: 'Sarah Kim',
        case_type: 'custody',
        summary: 'Divorced mother seeking modification of joint custody due to father’s substance abuse — multiple DUI arrests in past 6 months. Child (age 9) has reported fear of staying at father’s home.',
        deadline_days: 10,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: ['Financial disclosure statements', 'Child psychologist evaluation', 'School attendance records'],
        priority_score: 62,
        score_breakdown: { deadline_points: 20, vulnerability_points: 15, case_type_points: 18, similarity_points: 9 },
        priority_reason: 'Custody modification with 10-day hearing date requires complete evidentiary package. Missing financial disclosure and psychological evaluation will result in continued hearing — delays put child at risk.',
        similar_cases: [
          { id: 'h018', outcome: 'Custody modified to primary custody pending evaluation', similarity: 0.73 },
        ],
        recommendation: 'Obtain emergency child psychological evaluation before hearing. File financial disclosure statement immediately. Gather school records documenting impact of custody arrangement.',
        rank: 16,
        status: 'pending',
      },
      {
        client_name: 'Robert Johnson',
        case_type: 'other',
        summary: 'Veteran with service-connected PTSD and traumatic brain injury denied Social Security Disability — determination made without reviewing VA disability rating. Benefits termination appeal requires complete medical record.',
        deadline_days: 9,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: ['Disability determination letter', 'Medical records from treating physician', 'Work history documentation'],
        priority_score: 63,
        score_breakdown: { deadline_points: 22, vulnerability_points: 12, case_type_points: 12, similarity_points: 10 },
        priority_reason: 'SSDI appeal hearing in 9 days with incomplete medical record. VA disability rating (80%) was not submitted in original application — this alone may be determinative. Missing records risk adverse decision.',
        similar_cases: [
          { id: 'h019', outcome: 'SSDI approved on appeal — VA records were determinative', similarity: 0.81 },
        ],
        recommendation: 'Request emergency medical record subpoena from VA. Submit VA disability rating letter to SSA immediately. Prepare veterans preference argument for administrative law judge.',
        rank: 17,
        status: 'pending',
      },
      {
        client_name: 'Elena Rodriguez',
        case_type: 'wage_theft',
        summary: 'Home health aide claims $22,000 in unpaid overtime from private family employer. Cash payments with no documentation — employer disputes all hours claimed. Client kept personal diary of work hours.',
        deadline_days: 12,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: ['Pay stub copies (last 12 months)', 'Employment contract', 'Time tracking records', 'Witness statements'],
        priority_score: 57,
        score_breakdown: { deadline_points: 16, vulnerability_points: 8, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'Wage claim with significant evidentiary challenges — missing payroll records place burden on client testimony. Personal diary may substitute but supporting documentation needed before filing deadline.',
        similar_cases: [
          { id: 'h020', outcome: 'Wage claim upheld — personal records accepted as evidence', similarity: 0.71 },
        ],
        recommendation: 'Submit personal diary and bank deposit records as substitute payroll evidence. Interview other household employees as witnesses. File complaint with private right of action as diary constitutes business record.',
        rank: 18,
        status: 'pending',
      },
      {
        client_name: 'David Thompson',
        case_type: 'immigration',
        summary: 'Guatemalan indigenous rights activist seeking asylum based on credible threats from organized crime after testifying at corruption trial. Previous attorney withdrew — client has 8 days to file asylum application.',
        deadline_days: 8,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: ['Country conditions evidence', 'Expert witness declaration', 'Prior persecution documentation'],
        priority_score: 64,
        score_breakdown: { deadline_points: 24, vulnerability_points: 5, case_type_points: 18, similarity_points: 8 },
        priority_reason: 'Asylum application deadline in 8 days with missing country conditions evidence — essential for establishing nexus between persecution and protected ground. Expert declaration on Guatemala organized crime patterns needed urgently.',
        similar_cases: [],
        recommendation: 'File asylum application with available evidence — missing docs can supplement later. Contact human rights organizations for emergency country conditions declaration. Request pro bono immigration expert.',
        rank: 19,
        status: 'pending',
      },
      {
        client_name: 'Laila Hassan',
        case_type: 'eviction',
        summary: 'Somali refugee family of six in verbal lease arrangement with slumlord. Eviction served after complaining to city about mold and vermin. Retaliatory eviction claim requires documentation client may not have.',
        deadline_days: 11,
        vulnerability_flags: { minor_children: true, language_barrier: true, medical_condition: false },
        missing_info: ['Lease agreement (client has verbal lease)', 'Rent payment receipts', 'Habitability complaint records'],
        priority_score: 59,
        score_breakdown: { deadline_points: 18, vulnerability_points: 18, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'Retaliatory eviction for habitability complaint — strong legal basis but missing documentation of both the complaints and the lease terms. 11-day window to build evidentiary record.',
        similar_cases: [
          { id: 'h021', outcome: 'Retaliatory eviction defense upheld — habitability complaints documented', similarity: 0.77 },
        ],
        recommendation: 'Obtain city inspection records (public record) documenting habitability complaints. Locate witnesses to verbal lease terms. File retaliatory eviction defense citing city inspection history.',
        rank: 20,
        status: 'pending',
      },

      // ── MEDIUM PRIORITY (rank 21-40, score 40-64) ───────────────────────────
      {
        client_name: 'Marcus Bell',
        case_type: 'employment',
        summary: 'Former warehouse manager alleges disability discrimination after being denied ergonomic workstation accommodation. Terminated 3 weeks after formal accommodation request.',
        deadline_days: 14,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: [],
        priority_score: 52,
        score_breakdown: { deadline_points: 16, vulnerability_points: 8, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'ADA accommodation denial followed by termination — strong temporal nexus. 14-day window to file EEOC charge before state deadline.',
        similar_cases: [],
        recommendation: 'File EEOC disability discrimination charge. Document accommodation request timeline. Preserve termination notice as evidence of temporal proximity.',
        rank: 21,
        status: 'pending',
      },
      {
        client_name: 'Aisha Mensah',
        case_type: 'custody',
        summary: 'Grandmother seeking legal guardianship of two grandchildren (ages 3 and 6) after both parents incarcerated. Children currently in county foster care — kinship placement preferred.',
        deadline_days: 13,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: ['Kinship assessment', 'Background check clearance'],
        priority_score: 58,
        score_breakdown: { deadline_points: 18, vulnerability_points: 18, case_type_points: 14, similarity_points: 8 },
        priority_reason: 'Children in foster care with available kinship placement — kinship preference under ICWA and state law favors expedited guardianship. 13-day window before next foster placement review.',
        similar_cases: [],
        recommendation: 'File kinship guardianship petition immediately. Request emergency kinship assessment from county. Expedite background check clearance.',
        rank: 22,
        status: 'pending',
      },
      {
        client_name: 'Carlos Fuentes',
        case_type: 'wage_theft',
        summary: 'Landscaping crew leader owed $8,200 in unpaid overtime from subcontracting arrangement. Contractor claims crew members are independent contractors — misclassification evident.',
        deadline_days: 18,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 48,
        score_breakdown: { deadline_points: 14, vulnerability_points: 5, case_type_points: 16, similarity_points: 9 },
        priority_reason: 'Worker misclassification with 18-day window. ABC test establishes employee status — damages include overtime, benefits, and penalties.',
        similar_cases: [],
        recommendation: 'File wage claim citing employee misclassification under ABC test. Request joint employer liability analysis of general contractor.',
        rank: 23,
        status: 'pending',
      },
      {
        client_name: 'Jennifer Walsh',
        case_type: 'eviction',
        summary: 'Tenant in rent-controlled unit facing eviction for "owner move-in" — landlord\'s adult child claims they will occupy unit but owns property in same building with vacant units.',
        deadline_days: 15,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 51,
        score_breakdown: { deadline_points: 18, vulnerability_points: 0, case_type_points: 20, similarity_points: 10 },
        priority_reason: 'Owner move-in eviction may be pretextual — landlord’s family member owns other units in building. 15-day window to file challenge before relocation assistance waived.',
        similar_cases: [],
        recommendation: 'File eviction defense citing bad faith owner move-in. Document vacant units owned by landlord’s family. Research local owner move-in ordinance requirements.',
        rank: 24,
        status: 'pending',
      },
      {
        client_name: 'Raj Krishnamurthy',
        case_type: 'immigration',
        summary: 'H-1B worker\'s employer filed visa extension 8 months late — applicant working in gap period. Now facing USCIS review for unauthorized work period.',
        deadline_days: 20,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['Employment verification letters', 'I-94 travel history'],
        priority_score: 44,
        score_breakdown: { deadline_points: 12, vulnerability_points: 0, case_type_points: 18, similarity_points: 10 },
        priority_reason: 'Potential unauthorized work finding — employer error created gap in authorized status. 20-day response deadline to USCIS RFE.',
        similar_cases: [],
        recommendation: 'Respond to USCIS RFE documenting employer error. File employer liability claim for costs of immigration consequence. Request USCIS discretionary forgiveness.',
        rank: 25,
        status: 'pending',
      },
      {
        client_name: 'Patricia Moore',
        case_type: 'other',
        summary: 'Disabled veteran denied VA housing assistance despite qualifying service-connected disability. Administrative error in medical classification requires appeal.',
        deadline_days: 16,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: ['Updated medical assessment', 'VA housing determination letter'],
        priority_score: 50,
        score_breakdown: { deadline_points: 16, vulnerability_points: 10, case_type_points: 12, similarity_points: 9 },
        priority_reason: 'VA administrative error denying qualified veteran housing benefits. 16-day appeal window — straightforward correction with strong precedent.',
        similar_cases: [],
        recommendation: 'File VA housing appeal with updated medical assessment. Request expedited review citing service-connected disability status.',
        rank: 26,
        status: 'pending',
      },
      {
        client_name: 'Liam O\'Brien',
        case_type: 'employment',
        summary: 'Union electrician retaliated against after filing OSHA complaint about unguarded electrical panels. Reassigned to night shift, pay reduced 15%.',
        deadline_days: 12,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 55,
        score_breakdown: { deadline_points: 18, vulnerability_points: 0, case_type_points: 14, similarity_points: 12 },
        priority_reason: 'OSHA retaliation with documented adverse employment action within 30-day filing window. Pay reduction and shift reassignment create strong temporal nexus claim.',
        similar_cases: [],
        recommendation: 'File OSHA retaliation complaint within 30-day window. Document pay reduction and shift change as adverse actions. Notify union representative of retaliation claim.',
        rank: 27,
        status: 'pending',
      },
      {
        client_name: 'Sunita Sharma',
        case_type: 'custody',
        summary: 'Non-citizen mother seeking custody of U.S. citizen child. Father threatening to claim mother’s immigration status would prevent custody award — legally incorrect but creates urgency.',
        deadline_days: 22,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: ['Immigration status documentation', 'Child citizenship certificate'],
        priority_score: 42,
        score_breakdown: { deadline_points: 10, vulnerability_points: 15, case_type_points: 12, similarity_points: 8 },
        priority_reason: 'Immigration status is irrelevant to custody determination — educating court prevents erroneous adverse ruling. 22-day custody hearing requires preemptive briefing.',
        similar_cases: [],
        recommendation: 'File motion in limine to exclude immigration status evidence. Submit legal brief on immigration-neutral custody standards. Obtain child’s citizenship documentation.',
        rank: 28,
        status: 'pending',
      },
      {
        client_name: 'Tyrone Jackson',
        case_type: 'wage_theft',
        summary: 'Delivery driver misclassified as independent contractor denied overtime and mileage reimbursement for 18 months. ABC test clearly establishes employee status.',
        deadline_days: 19,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 45,
        score_breakdown: { deadline_points: 12, vulnerability_points: 0, case_type_points: 16, similarity_points: 10 },
        priority_reason: 'Delivery driver misclassification — ABC test plainly establishes employee status. 19-day filing window for state wage claim covering 18 months of damages.',
        similar_cases: [],
        recommendation: 'File state wage claim under ABC test misclassification theory. Calculate 18 months of overtime and mileage reimbursement. Include liquidated damages in claim amount.',
        rank: 29,
        status: 'pending',
      },
      {
        client_name: 'Hannah Kim',
        case_type: 'eviction',
        summary: 'Mother of child with autism spectrum disorder facing eviction from accessible ground-floor unit. Landlord converted building to condos — tenant claims retaliation for accommodation request.',
        deadline_days: 24,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: true },
        missing_info: [],
        priority_score: 47,
        score_breakdown: { deadline_points: 10, vulnerability_points: 18, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'Fair Housing Act accommodation request followed by condo conversion — retaliatory nexus. Child’s disability creates compelling accommodation defense.',
        similar_cases: [],
        recommendation: 'File Fair Housing Act complaint. Assert reasonable accommodation defense to eviction. Request HUD investigation of conversion-related retaliation.',
        rank: 30,
        status: 'pending',
      },
      {
        client_name: 'Fernando Castillo',
        case_type: 'immigration',
        summary: 'Mexican national with 20-year LPR status facing deportation for decade-old drug possession conviction under newly retroactive enforcement interpretation.',
        deadline_days: 17,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: ['Conviction records', 'Clemency application materials'],
        priority_score: 49,
        score_breakdown: { deadline_points: 14, vulnerability_points: 5, case_type_points: 18, similarity_points: 9 },
        priority_reason: 'Retroactive enforcement of decade-old conviction — constitutional due process arguments apply. 17-day window for removal defense filing.',
        similar_cases: [],
        recommendation: 'File removal defense citing retroactive application of enforcement policy. Explore post-conviction relief for underlying conviction. Request prosecutorial discretion from ICE.',
        rank: 31,
        status: 'pending',
      },
      {
        client_name: 'Olivia Grant',
        case_type: 'employment',
        summary: 'Pregnant employee placed on "light duty" against her wishes and denied regular pay rate — constructive demotion during pregnancy constitutes discrimination.',
        deadline_days: 21,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 43,
        score_breakdown: { deadline_points: 10, vulnerability_points: 5, case_type_points: 14, similarity_points: 10 },
        priority_reason: 'Pregnancy Discrimination Act violation — involuntary light duty with pay reduction constitutes adverse action. 21-day window to file EEOC charge.',
        similar_cases: [],
        recommendation: 'File EEOC charge under Pregnancy Discrimination Act. Document involuntary light duty assignment and pay differential. Request immediate reinstatement to regular duties.',
        rank: 32,
        status: 'pending',
      },
      {
        client_name: 'Sven Anderson',
        case_type: 'other',
        summary: 'Student loan borrower enrolled in Public Service Loan Forgiveness program denied forgiveness after 10 years of qualifying payments — servicer error in payment counting.',
        deadline_days: 14,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['Payment history records', 'Employer certification forms', 'PSLF application'],
        priority_score: 53,
        score_breakdown: { deadline_points: 16, vulnerability_points: 0, case_type_points: 12, similarity_points: 12 },
        priority_reason: 'PSLF denial after 10 years of qualifying payments — servicer error in payment counting is correctable through reconsideration. 14-day reconsideration window.',
        similar_cases: [],
        recommendation: 'File PSLF reconsideration request with complete payment history. Submit employer certification for all qualifying employment periods. Escalate to FSA ombudsman if denied.',
        rank: 33,
        status: 'pending',
      },
      {
        client_name: 'Alyssa Torres',
        case_type: 'eviction',
        summary: 'Single father of three in HUD subsidized housing faces eviction for lease violation — installed a baby gate in hallway, classified as "structural modification" by property manager.',
        deadline_days: 25,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 41,
        score_breakdown: { deadline_points: 10, vulnerability_points: 12, case_type_points: 14, similarity_points: 8 },
        priority_reason: 'HUD eviction for baby gate installation — safety device not a structural modification under HUD regulations. Strong defense with 25-day response window.',
        similar_cases: [],
        recommendation: 'File HUD grievance challenging structural modification classification. Cite HUD regulations distinguishing safety devices. Request informal hearing under HUD procedures.',
        rank: 34,
        status: 'pending',
      },
      {
        client_name: 'Benjamin Wright',
        case_type: 'wage_theft',
        summary: 'Restaurant manager denied overtime pay by employer who misclassified him as "exempt executive" despite spending 80% of time on non-managerial tasks.',
        deadline_days: 16,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 50,
        score_breakdown: { deadline_points: 16, vulnerability_points: 0, case_type_points: 16, similarity_points: 11 },
        priority_reason: 'Executive exemption misclassification — duties test fails when 80% of time spent on non-exempt tasks. 16-day filing window for FLSA claim.',
        similar_cases: [],
        recommendation: 'File FLSA overtime claim based on duties test failure. Document time allocation showing predominantly non-exempt tasks. Include two-year lookback period in damages calculation.',
        rank: 35,
        status: 'pending',
      },
      {
        client_name: 'Grace Nakamura',
        case_type: 'custody',
        summary: 'Japanese national co-parent attempting to relocate internationally with child — Hague Convention filing requires immediate response to prevent unauthorized removal.',
        deadline_days: 20,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: ['Existing custody order', 'Travel document copies'],
        priority_score: 44,
        score_breakdown: { deadline_points: 12, vulnerability_points: 12, case_type_points: 14, similarity_points: 8 },
        priority_reason: 'International parental abduction risk — Hague Convention filing must precede any international travel. 20-day window to obtain ne exeat order.',
        similar_cases: [],
        recommendation: 'File Hague Convention petition with Central Authority. Obtain emergency ne exeat order preventing international travel. Surrender child’s passport to court.',
        rank: 36,
        status: 'pending',
      },
      {
        client_name: 'Isaiah Thompson',
        case_type: 'employment',
        summary: 'Black educator denied tenure despite meeting all criteria — pattern of minority educator denial at institution documented in prior EEOC charges.',
        deadline_days: 23,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 41,
        score_breakdown: { deadline_points: 10, vulnerability_points: 5, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'Racial discrimination in tenure denial with documented institutional pattern. 23-day window to file EEOC charge connecting to prior institutional charges.',
        similar_cases: [],
        recommendation: 'File EEOC charge citing institutional pattern of racial discrimination in tenure decisions. Obtain prior EEOC charge records from institution. Explore class action basis with prior complainants.',
        rank: 37,
        status: 'pending',
      },
      {
        client_name: 'Mei Zhang',
        case_type: 'immigration',
        summary: 'Chinese national with pending green card application denied employment authorization renewal — processing delay stranded her status for 8 months.',
        deadline_days: 15,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 52,
        score_breakdown: { deadline_points: 18, vulnerability_points: 5, case_type_points: 18, similarity_points: 8 },
        priority_reason: 'EAD renewal denial despite pending adjustment of status — USCIS processing delay created unauthorized work gap. 15-day window for mandamus action.',
        similar_cases: [],
        recommendation: 'File mandamus action to compel USCIS processing of EAD renewal. Request expedited processing based on economic necessity. File congressional inquiry through representative’s office.',
        rank: 38,
        status: 'pending',
      },
      {
        client_name: 'Nathan Cooper',
        case_type: 'other',
        summary: 'Low-income homeowner facing tax lien foreclosure for $3,200 in unpaid property taxes — lender failed to pay from escrow account, denies responsibility.',
        deadline_days: 18,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['Escrow statements', 'Mortgage servicing correspondence'],
        priority_score: 46,
        score_breakdown: { deadline_points: 14, vulnerability_points: 0, case_type_points: 12, similarity_points: 12 },
        priority_reason: 'Tax lien foreclosure caused by lender escrow failure — lender bears responsibility under RESPA. 18-day redemption period before foreclosure completes.',
        similar_cases: [],
        recommendation: 'File RESPA claim against mortgage servicer for escrow mismanagement. Pay tax lien to stop foreclosure pending servicer reimbursement. File complaint with CFPB.',
        rank: 39,
        status: 'pending',
      },
      {
        client_name: 'Fatou Diallo',
        case_type: 'eviction',
        summary: 'Gambian refugee in public housing facing eviction for hosting extended family during Ramadan — "overcrowding" charge conflicts with religious accommodation requirements.',
        deadline_days: 22,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 43,
        score_breakdown: { deadline_points: 10, vulnerability_points: 5, case_type_points: 14, similarity_points: 9 },
        priority_reason: 'Religious accommodation defense to overcrowding eviction — First Amendment and RLUIPA protections apply in public housing. 22-day response window.',
        similar_cases: [],
        recommendation: 'File religious accommodation request citing RLUIPA protections in public housing. Assert First Amendment defense to overcrowding charge. Contact HUD Office of Fair Housing.',
        rank: 40,
        status: 'pending',
      },

      // ── LOWER PRIORITY (rank 41-50, score 20-39) ────────────────────────────
      {
        client_name: 'Ryan Murphy',
        case_type: 'employment',
        summary: 'Former sales representative disputing non-compete agreement with prior employer — overly broad geographic and duration restrictions likely unenforceable.',
        deadline_days: 28,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 35,
        score_breakdown: { deadline_points: 8, vulnerability_points: 0, case_type_points: 14, similarity_points: 8 },
        priority_reason: 'Overbroad non-compete with 28-day injunction response deadline. Unenforceability arguments strong based on geographic scope and duration.',
        similar_cases: [],
        recommendation: 'File declaratory judgment action challenging non-compete enforceability. Document geographic and temporal overbreadth. Research state-specific blue-pencil doctrine.',
        rank: 41,
        status: 'pending',
      },
      {
        client_name: 'Diane Foster',
        case_type: 'custody',
        summary: 'Grandparent seeking visitation rights after estrangement from adult child — state statute requires threshold showing of harm before granting third-party visitation.',
        deadline_days: 32,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: ['Relationship history documentation'],
        priority_score: 31,
        score_breakdown: { deadline_points: 6, vulnerability_points: 10, case_type_points: 10, similarity_points: 8 },
        priority_reason: 'Grandparent visitation petition requires harm threshold showing. 32-day hearing date allows time to prepare compelling relationship history evidence.',
        similar_cases: [],
        recommendation: 'File grandparent visitation petition with documented relationship history. Prepare harm threshold showing for state statute requirements. Gather family photographs and communication records.',
        rank: 42,
        status: 'pending',
      },
      {
        client_name: 'Mohammed Al-Rashid',
        case_type: 'immigration',
        summary: 'Yemeni national seeking green card through employment-based preference — priority date retrogression created unexpected delay in approved petition.',
        deadline_days: 30,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 33,
        score_breakdown: { deadline_points: 6, vulnerability_points: 0, case_type_points: 18, similarity_points: 9 },
        priority_reason: 'Priority date retrogression creating indefinite delay — 30-day window to explore alternative pathways or parole in place options.',
        similar_cases: [],
        recommendation: 'Explore National Interest Waiver as alternative pathway. Research humanitarian parole eligibility. Monitor DOS Visa Bulletin for priority date movement.',
        rank: 43,
        status: 'pending',
      },
      {
        client_name: 'Angela Davis',
        case_type: 'other',
        summary: 'Cancer patient disputing insurance denial for experimental treatment — oncologist letter of medical necessity submitted, insurer claims treatment not "proven effective."',
        deadline_days: 35,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: true },
        missing_info: ['Clinical trial enrollment records', 'Second physician opinion'],
        priority_score: 29,
        score_breakdown: { deadline_points: 4, vulnerability_points: 8, case_type_points: 10, similarity_points: 7 },
        priority_reason: 'Insurance denial for cancer treatment with 35-day external appeal deadline. Clinical trial evidence may overcome "not proven effective" standard.',
        similar_cases: [],
        recommendation: 'File external appeal with state insurance commissioner. Supplement with clinical trial data and second physician opinion. Research state external review requirements for cancer treatment.',
        rank: 44,
        status: 'pending',
      },
      {
        client_name: 'Kevin Park',
        case_type: 'wage_theft',
        summary: 'Nail salon worker claims illegal deduction of "product fees" from wages — employer deducts flat daily fee regardless of products used.',
        deadline_days: 27,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 37,
        score_breakdown: { deadline_points: 8, vulnerability_points: 5, case_type_points: 14, similarity_points: 8 },
        priority_reason: 'Illegal wage deduction with 27-day filing window. Flat product fee deductions violate minimum wage floor provisions.',
        similar_cases: [],
        recommendation: 'File state wage claim for illegal deductions. Document fee amounts and calculate deductions against minimum wage floor. Report to state labor board.',
        rank: 45,
        status: 'pending',
      },
      {
        client_name: 'Sandra Williams',
        case_type: 'eviction',
        summary: 'Long-term tenant of 15 years receiving non-renewal notice in rent-controlled jurisdiction — landlord must show just cause under local ordinance.',
        deadline_days: 40,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: ['Lease history', 'Prior renewal notices'],
        priority_score: 25,
        score_breakdown: { deadline_points: 4, vulnerability_points: 0, case_type_points: 14, similarity_points: 7 },
        priority_reason: 'Just cause eviction ordinance protects 15-year tenant. 40-day window to respond to non-renewal and assert just cause requirement.',
        similar_cases: [],
        recommendation: 'Assert just cause protection under local rent control ordinance. Document 15-year tenancy and payment history. Request landlord’s stated just cause basis in writing.',
        rank: 46,
        status: 'pending',
      },
      {
        client_name: 'David Lee',
        case_type: 'employment',
        summary: 'HR professional documenting systemic age discrimination in layoff selection — personal claim plus potential class action basis.',
        deadline_days: 33,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 30,
        score_breakdown: { deadline_points: 6, vulnerability_points: 0, case_type_points: 12, similarity_points: 10 },
        priority_reason: 'Age discrimination with class action potential — HR insider has systemic documentation others lack. 33-day EEOC filing window.',
        similar_cases: [],
        recommendation: 'File ADEA charge with EEOC. Preserve systemic layoff data as evidence. Consult class action employment counsel on collective action potential.',
        rank: 47,
        status: 'pending',
      },
      {
        client_name: 'Rosa Parks',
        case_type: 'immigration',
        summary: 'Guatemalan asylum seeker with approved claim awaiting final interview scheduling — USCIS backlog of 18 months, requesting humanitarian parole.',
        deadline_days: 38,
        vulnerability_flags: { minor_children: false, language_barrier: true, medical_condition: false },
        missing_info: [],
        priority_score: 27,
        score_breakdown: { deadline_points: 4, vulnerability_points: 5, case_type_points: 10, similarity_points: 8 },
        priority_reason: 'Approved asylum claim in USCIS interview backlog — humanitarian parole request may bridge gap. 38-day window for parole application.',
        similar_cases: [],
        recommendation: 'File humanitarian parole application with approved asylum claim documentation. Submit congressional inquiry through representative to expedite interview scheduling.',
        rank: 48,
        status: 'pending',
      },
      {
        client_name: 'James Carter',
        case_type: 'other',
        summary: 'Tenant in mobile home park facing eviction for organizing residents — state law protects tenant organizing activity in mobile home parks.',
        deadline_days: 29,
        vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 34,
        score_breakdown: { deadline_points: 6, vulnerability_points: 0, case_type_points: 12, similarity_points: 10 },
        priority_reason: 'Mobile home park tenant organizing retaliation — state statute protects organizing activity. 29-day eviction response window.',
        similar_cases: [],
        recommendation: 'File eviction defense under mobile home park tenant organizing protection statute. Document organizing activity timeline. Request injunctive relief to prevent retaliatory eviction.',
        rank: 49,
        status: 'pending',
      },
      {
        client_name: 'Maria Gonzalez',
        case_type: 'eviction',
        summary: 'Family facing lease non-renewal in neighborhood undergoing gentrification — no just cause in non-rent-controlled area, exploring negotiated move assistance.',
        deadline_days: 45,
        vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
        missing_info: [],
        priority_score: 22,
        score_breakdown: { deadline_points: 2, vulnerability_points: 8, case_type_points: 8, similarity_points: 4 },
        priority_reason: 'Non-renewal in uncontrolled area — limited legal defense but negotiated relocation assistance possible. 45-day window for negotiation before formal eviction proceedings.',
        similar_cases: [],
        recommendation: 'Negotiate relocation assistance with landlord citing family with minor children. Research city relocation assistance programs. Explore tenant organizing options in gentrifying neighborhood.',
        rank: 50,
        status: 'pending',
      },
    ]

    const now = new Date()
    const cases = SEED_CASES.map((c) => ({
      ...c,
      uid: decoded.uid,
      batch_id: 'demo_seed',
      mongodb_via: 'demo_seed',
      outreach: { status: 'none' },
      calendar: { status: 'none' },
      brief: { available: false },
      agent_trace: [],
      raw_text: c.summary,
      createdAt: now,
      updatedAt: now,
    }))

    await Case.insertMany(cases, { ordered: false })
    return Response.json({ seeded: cases.length, message: 'Demo dataset loaded successfully' })
  } catch (err) {
    console.error('[demo/seed POST]', err.message)
    return apiError('Seed failed', 500)
  }
}
