// Standalone seed script — inserts 30 past_cases with auto-embeddings via MongoDB MCP
import 'dotenv/config'
import mongoose from 'mongoose'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))

async function seed() {
  const uri = process.env.MONGODB_URI
  if (!uri) throw new Error('MONGODB_URI is not set in environment')

  console.log('Connecting to MongoDB...')
  await mongoose.connect(uri)
  const db = mongoose.connection.db

  const collection = db.collection('past_cases')
  const existing = await collection.countDocuments()

  if (existing >= 30) {
    console.log(`Skipping seed — past_cases already has ${existing} documents.`)
    await mongoose.disconnect()
    return
  }

  const rawData = readFileSync(join(__dirname, 'data', 'past_cases.json'), 'utf8')
  const cases = JSON.parse(rawData)

  console.log(`Seeding ${cases.length} past cases...`)
  await collection.deleteMany({})
  await collection.insertMany(cases)
  console.log('Documents inserted.')

  // Create Atlas Vector Search index if it does not exist
  console.log('Checking vector search index...')
  try {
    const indexes = await collection.listSearchIndexes().toArray()
    const indexExists = indexes.some((idx) => idx.name === 'description_vector_index')

    if (!indexExists) {
      console.log('Creating vector search index...')
      await collection.createSearchIndex({
        name: 'description_vector_index',
        type: 'vectorSearch',
        definition: {
          fields: [
            {
              type: 'vector',
              path: 'description_embedding',
              numDimensions: 1024,
              similarity: 'cosine',
            },
          ],
        },
      })
      console.log('Vector search index created. Atlas will build it in the background.')
      console.log('NOTE: embeddings will be auto-generated by Atlas if Voyage AI is configured as the embedding provider.')
    } else {
      console.log('Vector search index already exists.')
    }
  } catch (err) {
    console.warn('Could not manage vector search index (may require Atlas M10+):', err.message)
  }

  console.log('Done. 30 past cases seeded.')
  await mongoose.disconnect()
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
