// Generate 1-page printable case brief using Gemini Pro
// Returns HTML that the browser can print-to-PDF natively — zero dependencies
import { callGeminiPro } from './gemini.js'

export async function generateBriefContent(caseData) {
  const topCase = caseData.similar_cases?.[0]

  const prompt = `You are writing a case brief for a legal aid attorney who has 5 minutes to prepare for a client consultation.

Case type: ${caseData.case_type}
Priority score: ${caseData.priority_score}/100
Summary: ${caseData.extracted?.summary}
Deadline: ${caseData.extracted?.deadline_days ?? 'unknown'} days
Vulnerability factors: ${[
  caseData.extracted?.vulnerability_flags?.minor_children  && 'minor children present',
  caseData.extracted?.vulnerability_flags?.language_barrier && 'language barrier',
  caseData.extracted?.vulnerability_flags?.medical_condition && 'medical condition',
].filter(Boolean).join(', ') || 'none identified'}
Missing documents: ${caseData.extracted?.missing_info?.join(', ') || 'none'}
${topCase
  ? `Similar past case: ${topCase.description || topCase.outcome_notes || ''}
Past outcome: ${topCase.outcome}
What worked: ${topCase.outcome_notes || 'No notes'}`
  : 'No similar past case found.'}
AI recommendation: ${caseData.recommendation || 'None generated.'}

Write exactly four sections with these exact headings:

1. CLIENT SITUATION
2. LEGAL CONTEXT
3. PRECEDENT
4. RECOMMENDED FIRST STEPS

Each section: 2-4 sentences or bullet points. Be specific, direct, and practical. Write for an attorney. No hedging. No AI disclaimers. No legal advice disclaimers.`

  return callGeminiPro(prompt)
}

export function buildBriefHTML(caseData, briefContent) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const sections = briefContent
    .split(/\n(?=\d\.\s)/)
    .map((s) => s.trim())
    .filter(Boolean)

  const sectionsHTML = sections.map((section) => {
    const firstLine = section.split('\n')[0]
    const rest      = section.split('\n').slice(1).join('\n').trim()
    return `
    <div class="section">
      <div class="section-heading">${firstLine}</div>
      <div class="section-body">${rest.replace(/\n/g, '<br>')}</div>
    </div>`
  }).join('')

  const bd = caseData.urgency_breakdown || caseData.score_breakdown || {}

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Case Brief — ${caseData.case_type} — Priority ${caseData.priority_score}</title>
  <style>
    @media print {
      @page { margin: 60px; size: letter; }
      body { -webkit-print-color-adjust: exact; }
    }
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 11px; color: #1a1714; line-height: 1.6;
      max-width: 680px; margin: 0 auto; padding: 48px 0;
    }
    .header {
      display: flex; justify-content: space-between; align-items: flex-start;
      margin-bottom: 8px;
    }
    .header-label {
      font-family: monospace; font-size: 9px; letter-spacing: 0.1em;
      text-transform: uppercase; color: #8a837a;
    }
    .rule { border: none; border-top: 0.5px solid #c8c1b4; margin: 12px 0; }
    .case-type {
      font-size: 18px; font-weight: 600; color: #1a1714;
      text-transform: uppercase; letter-spacing: 0.04em;
    }
    .priority {
      font-size: 11px; font-family: monospace;
      color: ${(caseData.priority_score ?? 0) >= 80 ? '#8b1a1a' : '#7a5c1e'};
      margin-top: 4px;
    }
    .summary { font-size: 11px; color: #4a4540; margin-top: 8px; margin-bottom: 4px; }
    .score-row {
      font-family: monospace; font-size: 9px; color: #8a837a;
      letter-spacing: 0.04em; text-transform: uppercase; margin-bottom: 16px;
    }
    .section { margin-bottom: 14px; }
    .section-heading {
      font-family: monospace; font-size: 9px; letter-spacing: 0.1em;
      text-transform: uppercase; color: #8a837a; margin-bottom: 4px;
      border-bottom: 0.5px solid #e0dbd0; padding-bottom: 3px;
    }
    .section-body { font-size: 11px; color: #1a1714; line-height: 1.65; }
    .footer {
      margin-top: 24px; font-family: monospace; font-size: 8px;
      color: #8a837a; text-align: center;
      border-top: 0.5px solid #e0dbd0; padding-top: 8px;
    }
  </style>
</head>
<body>
  <div class="header">
    <span class="header-label">JusticeQueue Case Brief</span>
    <span class="header-label">${date}</span>
  </div>
  <hr class="rule">
  <div class="case-type">${caseData.case_type.replace('_', ' ')}</div>
  <div class="priority">PRIORITY SCORE: ${caseData.priority_score}/100</div>
  <div class="summary">${caseData.extracted?.summary || caseData.summary || ''}</div>
  <div class="score-row">
    Deadline ${bd.deadline_points || 0} + Vulnerability ${bd.vulnerability_points || 0} + Case type ${bd.case_type_points || 0} + Precedent ${bd.similarity_points || 0} = ${caseData.priority_score}/100
  </div>
  <hr class="rule">
  ${sectionsHTML}
  <div class="footer">
    Generated by JusticeQueue &nbsp;·&nbsp; For caseworker use only &nbsp;·&nbsp; Not legal advice
  </div>
</body>
</html>`
}
