// GET /api/demo/queue — hardcoded 5-case demo queue, no auth required
export const dynamic = 'force-dynamic'

const DEMO_CASES = [
  {
    id: 'demo-001',
    rank: 1,
    client_name: 'Rodriguez Family',
    case_type: 'eviction',
    summary: 'Family of four including two minor children facing eviction in 48 hours after landlord refused payment plan following primary earner hospitalization.',
    deadline_days: 2,
    vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
    priority_score: 98,
    score_breakdown: { deadline: 40, vulnerability: 15, case_type: 18, similarity: 15, base: 10 },
    priority_reason: 'Court date in 48 hours. Minor children at risk of housing loss. Similar cases won when represented.',
    recommendation: 'Assign immediately. Court appearance in 48 hours with two minor children present. Request emergency continuance and document the hospitalization with medical records. This case profile matches our highest win-rate eviction cases.',
    similar_cases: [
      { case_type: 'eviction', outcome: 'won', outcome_notes: 'Emergency continuance granted; family kept housing after payment plan negotiated', similarity_score: 0.94 },
    ],
    missing_info: [],
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'demo-002',
    rank: 2,
    client_name: 'Anh Nguyen',
    case_type: 'immigration',
    summary: 'Long-term resident of 19 years with final order of removal and 72-hour deadline to file motion to reopen after attorney error; US-born daughter has serious medical condition.',
    deadline_days: 3,
    vulnerability_flags: { minor_children: false, language_barrier: true, medical_barrier: false },
    priority_score: 93,
    score_breakdown: { deadline: 40, vulnerability: 10, case_type: 20, similarity: 8, base: 15 },
    priority_reason: '72-hour deadline for motion to reopen. Attorney error creates strong grounds for relief. Language barrier present.',
    recommendation: 'Assign to immigration specialist today. Attorney error at missed hearing is well-established grounds for motion to reopen — file immediately. Gather documentation of daughter\'s medical condition as hardship evidence.',
    similar_cases: [
      { case_type: 'immigration', outcome: 'won', outcome_notes: 'Motion to reopen granted based on attorney ineffective assistance; removal order vacated', similarity_score: 0.88 },
    ],
    missing_info: ['Attorney name and bar number for ineffective assistance claim'],
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'demo-003',
    rank: 3,
    client_name: 'Keisha Brown',
    case_type: 'custody',
    summary: 'Child not returned by ex-partner after scheduled visit 4 days ago; police report filed; emergency custody modification needed with 21-day family court wait.',
    deadline_days: 21,
    vulnerability_flags: { minor_children: true, language_barrier: false, medical_condition: false },
    priority_score: 71,
    score_breakdown: { deadline: 15, vulnerability: 15, case_type: 10, similarity: 8, base: 23 },
    priority_reason: 'Child may be in unsafe situation. Emergency ex parte motion may bypass the 21-day docket.',
    recommendation: 'File emergency ex parte motion for immediate custody order — the 4-day absence with no contact bypasses the standard docket timeline. The police report is critical supporting documentation.',
    similar_cases: [
      { case_type: 'custody', outcome: 'won', outcome_notes: 'Emergency ex parte granted same day; child returned within 24 hours', similarity_score: 0.79 },
    ],
    missing_info: ['Details of any prior custody order'],
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'demo-004',
    rank: 4,
    client_name: 'Marcus Webb',
    case_type: 'wage_theft',
    summary: 'Terminated without final two weeks wages; employer has documented state labor violations history; 14-day window to file with labor commissioner before employer closes.',
    deadline_days: 14,
    vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
    priority_score: 55,
    score_breakdown: { deadline: 15, vulnerability: 0, case_type: 12, similarity: 8, base: 20 },
    priority_reason: 'Employer closing imminently. Documented violation history strengthens claim significantly.',
    recommendation: 'File labor commissioner complaint within the week to ensure priority in any asset recovery. The employer\'s documented violation history makes this a strong claim.',
    similar_cases: [
      { case_type: 'wage_theft', outcome: 'won', outcome_notes: 'Full wages recovered plus penalties; employer had prior violation history', similarity_score: 0.82 },
    ],
    missing_info: ['Pay stubs or employment contract'],
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'demo-005',
    rank: 5,
    client_name: 'Jin Park',
    case_type: 'employment',
    summary: 'Constructively dismissed after raising safety violations; employer withheld COBRA notice and final paycheck; 30 days until statute of limitations on wrongful termination.',
    deadline_days: 30,
    vulnerability_flags: { minor_children: false, language_barrier: false, medical_condition: false },
    priority_score: 38,
    score_breakdown: { deadline: 0, vulnerability: 0, case_type: 8, similarity: 0, base: 30 },
    priority_reason: '30-day window before limitations period. COBRA and final paycheck violations add additional claims.',
    recommendation: 'Schedule intake within 2 weeks to preserve statute of limitations. Document all communications with HR about safety violations — this is the foundation of the retaliation claim.',
    similar_cases: [],
    missing_info: ['Written records of safety complaints to HR', 'Date of termination'],
    status: 'pending',
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
]

export async function GET() {
  return Response.json({ cases: DEMO_CASES, demo: true })
}
